### PR TITLE
bump scrypt package to ^6.0.1

### PR DESCRIPTION
**Pull request by sscotth**
Update fixes my build errors

### CODE REVIEW

**Comment by joepie91** [comment]
Thanks for your PR! I'll probably merge it, as it doesn't seem to introduce any obvious issues, but could you clarify (for the purposes of documentation) on what kind of build issues you ran into with the `5.x` branch of `scrypt`?

**Comment by sscotth** [comment]
Same as this issue: https://github.com/barrysteyn/node-scrypt/issues/98

**Comment by VictorioBerra** [comment]
+1 Pi Zero fails too

**Comment by joepie91** [comment]
Tested and released as 2.0.3, this issue should now be resolved.

**Pull request merged**
